security:
    encoders:
        App\Entity\Admin: bcrypt
        App\Entity\User: bcrypt
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        database_admin:
            entity: { class: App\Entity\Admin, property: username }
        database_user:
            entity: { class: App\Entity\User, property: username }
        users_in_memory: { memory: null }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin_secured_area:
            anonymous: ~
            pattern: ^/panel-admin
            provider: database_admin
            form_login:
                check_path: security_admin_login
                login_path: security_admin_login
                # csrf_token_generator: security.csrf.token_manager
                default_target_path: dashboard_admin_home
            logout:
                path: security_admin_logout
                target: security_admin_login

        user_secured_area:
            anonymous: ~
            pattern: ^/
            provider: database_user
            form_login:
                check_path: security_user_login
                login_path: security_user_login
                # csrf_token_generator: security.csrf.token_manager
                default_target_path: dashboard_user_informations
            logout:
                path: security_user_logout
                target: security_user_login

        main:
            anonymous: lazy
            provider: users_in_memory

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/panel-admin/accueil, roles: ROLE_ADMIN }
        - { path: ^/panel-admin/commandes, roles: ROLE_ADMIN }
        - { path: ^/panel-admin/livres, roles: ROLE_ADMIN }
        - { path: ^/panel-admin/boutique, roles: ROLE_ADMIN }
        - { path: ^/panel-admin/mentions, roles: ROLE_ADMIN }
        - { path: ^/panel-client/accueil, roles: ROLE_USER }
        - { path: ^/panel-client/informations, roles: ROLE_USER }
        - { path: ^/panel-client/adresses, roles: ROLE_USER }
        - { path: ^/panel-client/ajouter-adresses, roles: ROLE_USER }
        - { path: ^/panel-client/commandes, roles: ROLE_USER }
    
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
